//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public int ID { get; set; }
        public string NameUser { get; set; }
        public string RoleUser { get; set; }
        public string PasswordUser { get; set; }
    }
}
